// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://psvmngqfdoccgsuaijvt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBzdm1uZ3FmZG9jY2dzdWFpanZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjcxNjE5NTgsImV4cCI6MjA4MjczNzk1OH0.vuCZ2tWgh1pb1WEAqJP4TmTUNpso9Djo6foww8Jyrcc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});